import { mkdirSync, readdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs"
import { homedir } from "node:os"
import { join } from "node:path"
// The seam, spliced in at deploy time. Home Manager flattens each file to its
// own store path, so this relative import would resolve against the Nix store
// and fail to load — silently, because the loader discards the cause. The
// deployed artefact is therefore the two files concatenated, and `nix flake
// check` asserts this import was the one thing removed.
import {
  isRepeatUnload,
  shouldUnload,
  type Decision,
  type InflightEntry,
  type Lease,
  type LeaseSet,
} from "./decision.js"

/**
 * The plugin half of the unload policy.
 *
 * `decision.ts` holds the question; this file holds everything that answers it
 * in the real world: publishing what this instance knows, reading what the
 * others published, and issuing the unload. Everything time-dependent, mutable
 * or effectful lives here so the seam stays pure.
 *
 * Three facts about the host, each established by running a probe plugin
 * against opencode 1.18.31 rather than read off a changelog:
 *
 *  1. `event` delivery is filtered by working directory, so this instance can
 *     never see another's sessions. All cross-instance coordination goes
 *     through the lease directory.
 *  2. The plugin factory is invoked more than once per process. Leases,
 *     timers and the heartbeat are therefore behind a singleton guard; without
 *     it one process would publish two leases and run two unload timers.
 *  3. `session.idle` still exists but is deprecated. Liveness is read from
 *     `session.status`, which reports `busy` / `idle` / `retry`.
 */

const SERVICE = "llm-agent-unload-policy"

/** How often the policy re-reads the lease set and re-decides. */
const TICK_MS = 5_000

/** opencode invokes the factory more than once per process; this keys the singleton. */
const SINGLETON = Symbol.for("llm-agent.unload-policy.singleton")

type Level = "debug" | "info" | "warn" | "error"

type Logger = (level: Level, message: string, extra?: Record<string, unknown>) => void

type PolicyConfig = {
  idleThresholdSeconds: number
  settleSeconds: number
  backend: string
  /** Provider id whose models are served locally. Owned by the registry. */
  localProviderId: string
}

type SessionState = {
  /** Whether the model most recently seen for this session is served locally. */
  local: boolean
  busy: boolean
  busyAt: number
  model: string | null
}

/**
 * Only the event shapes this policy reads.
 *
 * `properties.sessionID` is top-level for message events even though the
 * published SDK types nest it under `info`/`part`; probed, not assumed.
 */
type OpencodeEvent = {
  type: string
  properties?: {
    sessionID?: string
    status?: { type: string }
    info?: { sessionID?: string }
  }
}

type ChatParamsInput = { sessionID: string; model?: { providerID?: string; id?: string } }

type PluginInput = {
  client: {
    app: {
      log(args: { body: { service: string; level: Level; message: string; extra?: Record<string, unknown> } }): unknown
    }
  }
  directory: string
}

type Hooks = {
  event?: (input: { event: OpencodeEvent }) => Promise<void>
  "chat.params"?: (input: ChatParamsInput) => Promise<void>
  dispose?: () => Promise<void>
  /** Test seam: one evaluation of the policy. Not called by opencode. */
  __tick?: () => Promise<{ decision: Decision; attempted: boolean }>
}

// --- paths -----------------------------------------------------------------

function home(): string {
  return process.env.HOME && process.env.HOME.length > 0 ? process.env.HOME : homedir()
}

/** Per-user state, not a temporary directory: leases must outlive a reboot. */
function stateDir(): string {
  return join(process.env.XDG_STATE_HOME ?? join(home(), ".local", "state"), "llm-agent")
}

function leaseDir(): string {
  return join(stateDir(), "leases")
}

function leasePath(instanceId: string): string {
  return join(leaseDir(), `${instanceId}.json`)
}

function heartbeatPath(): string {
  return join(stateDir(), "heartbeat.json")
}

/** Generated by the flake from the registry, so the thresholds are data. */
function policyConfigPath(): string {
  return join(home(), ".config", "llama-swap", "unload-policy.json")
}

// --- host probing ----------------------------------------------------------

let cachedBootId: string | null | undefined

/**
 * The kernel's boot id. A lease written before the last boot cannot be
 * attributed to a live process just because the pid has been reused, so the
 * boot id is part of what makes a lease trustworthy.
 */
function bootId(): string | null {
  if (cachedBootId !== undefined) return cachedBootId
  try {
    cachedBootId = readFileSync("/proc/sys/kernel/random/boot_id", "utf8").trim()
  } catch {
    cachedBootId = null
  }
  return cachedBootId
}

/**
 * Whether the process that wrote a lease still exists. A pid that exists but
 * was recycled belongs to somebody else, so the boot id has to agree too.
 */
function isProcessAlive(lease: { pid: number; bootId: string | null }): boolean {
  if (!Number.isInteger(lease.pid) || lease.pid <= 0) return false
  const current = bootId()
  if (current !== null && lease.bootId !== current) return false
  try {
    process.kill(lease.pid, 0)
    return true
  } catch (error) {
    // EPERM means the process exists but belongs to another user.
    return (error as { code?: string }).code === "EPERM"
  }
}

// --- lease publication -----------------------------------------------------

function writeJson(path: string, value: unknown): void {
  // Written through a temporary file so a reader never observes a half-written lease.
  const tmp = `${path}.tmp`
  writeFileSync(tmp, `${JSON.stringify(value)}\n`, { mode: 0o600 })
  renameSync(tmp, path)
}

function readLeaseSet(dir: string): LeaseSet {
  let names: string[]
  try {
    names = readdirSync(dir)
  } catch (error) {
    return { readable: false, error: `lease directory unreadable: ${String(error)}` }
  }

  const leases: Lease[] = []
  for (const name of names) {
    if (!name.endsWith(".json")) continue
    let parsed: Record<string, unknown>
    try {
      parsed = JSON.parse(readFileSync(join(dir, name), "utf8")) as Record<string, unknown>
    } catch (error) {
      // A lease that cannot be parsed is not a dead lease. It is an
      // unreadable lease set, and an unreadable lease set does not permit.
      return { readable: false, error: `lease '${name}' unreadable: ${String(error)}` }
    }
    leases.push({
      instanceId: String(parsed.instanceId ?? name),
      pid: Number(parsed.pid ?? -1),
      startedAt: Number(parsed.startedAt ?? 0),
      alive: isProcessAlive({ pid: Number(parsed.pid ?? -1), bootId: (parsed.bootId as string) ?? null }),
      lastLocalActivityAt: (parsed.lastLocalActivityAt as number | null) ?? null,
      busySince: (parsed.busySince as number | null) ?? null,
      idleSince: (parsed.idleSince as number | null) ?? null,
    })
  }
  return { readable: true, leases }
}

// --- the policy ------------------------------------------------------------

/**
 * Build the plugin.
 *
 * Exported separately from the singleton below so the wiring can be reasoned
 * about — and re-run in a test — without going through opencode's loader.
 */
export function createUnloadPolicy(
  input: PluginInput,
  config: PolicyConfig,
  instanceId: string,
  now: () => number = Date.now,
): Hooks {
  const log: Logger = (level, message, extra) => {
    try {
      input.client.app.log({ body: { service: SERVICE, level, message, extra } })
    } catch {
      console.log(`[${SERVICE}] ${level}: ${message}`)
    }
  }

  const pid = process.pid
  const boot = bootId()
  const startedAt = now()
  const sessions = new Map<string, SessionState>()

  let lastLocalActivityAt: number | null = null
  let busySince: number | null = null
  let idleSince: number | null = null
  let haveSeenStatus = false
  let lastUnloadAt: number | null = null
  let lastReason: string | null = null

  /**
   * Recompute the lease-level aggregates from the per-session states.
   *
   * `idleSince` is only advanced on the busy-to-idle *edge*. A turn that fails
   * or is cancelled can report idle more than once, and restarting the idle
   * clock on a duplicate would hold the resident model for a full threshold
   * after work that is already over.
   */
  function recompute(now: number): void {
    const all = [...sessions.values()]
    const busy = all.filter((s) => s.busy)
    const wasBusy = busySince !== null

    busySince = busy.length === 0 ? null : Math.min(...busy.map((s) => s.busyAt))

    if (busy.length > 0) {
      idleSince = null
    } else if (!haveSeenStatus || wasBusy) {
      idleSince = now
    }

    haveSeenStatus = true
  }

  function touchSession(sessionID: string, mutate: (state: SessionState, at: number) => void): void {
    const at = now()
    const state = sessions.get(sessionID) ?? { local: false, busy: false, busyAt: at, model: null }
    mutate(state, at)
    sessions.set(sessionID, state)
    recompute(at)
  }

  /** Record activity, but only when the session is running a local model. */
  function noteLocalActivity(state: SessionState): void {
    if (state.local) lastLocalActivityAt = now()
  }

  function publishLease(): void {
    const lease = {
      instanceId,
      pid,
      bootId: boot,
      startedAt,
      lastLocalActivityAt,
      busySince,
      idleSince,
    }
    try {
      mkdirSync(leaseDir(), { recursive: true, mode: 0o700 })
      writeJson(leasePath(instanceId), lease)
    } catch (error) {
      // Failing to publish is not fatal on its own, but it means this instance
      // cannot be seen by the others and so cannot contribute to a decision.
      log("warn", "could not publish lease", { error: String(error) })
    }
  }

  function writeHeartbeat(): void {
    try {
      mkdirSync(stateDir(), { recursive: true, mode: 0o700 })
      writeJson(heartbeatPath(), { at: now(), pid, instanceId })
    } catch (error) {
      log("warn", "could not write heartbeat", { error: String(error) })
    }
  }

  /**
   * Requests this instance knows are running.
   *
   * At this tier the only source available is its own session state: a local
   * session that is busy has a request against the backend. The backend's own
   * in-flight stream is the authoritative answer and replaces this in #50; the
   * decision's shape does not change when it does.
   */
  function inflightEntries(): InflightEntry[] {
    const entries: InflightEntry[] = []
    for (const [sessionID, state] of sessions) {
      if (state.busy && state.local) entries.push({ id: sessionID, model: state.model })
    }
    return entries
  }

  async function unload(): Promise<void> {
    try {
      const response = await fetch(`${config.backend}/api/models/unload`, { method: "POST" })
      log(response.ok ? "info" : "warn", "unload requested", { status: response.status })
    } catch (error) {
      log("warn", "unload request failed", { error: String(error) })
    }
  }

  /** What one evaluation decided and did. Lets a test assert the action, not just the intent. */
  type TickResult = { decision: Decision; attempted: boolean }

  async function tick(): Promise<TickResult> {
    const at = now()
    writeHeartbeat()
    publishLease()

    const leaseSet = readLeaseSet(leaseDir())
    const decision = shouldUnload(leaseSet, inflightEntries(), at, {
      idleThresholdMs: config.idleThresholdSeconds * 1000,
      settleMs: config.settleSeconds * 1000,
    })

    if (decision.reason !== lastReason) {
      lastReason = decision.reason
      log("debug", "unload decision", { unload: decision.unload, reason: decision.reason })
    }

    if (!decision.unload) return { decision, attempted: false }
    // One idle epoch yields one unload attempt, however many times the session
    // reports idle or however often the timer fires.
    if (isRepeatUnload(lastUnloadAt, leaseSet)) return { decision, attempted: false }

    lastUnloadAt = at
    await unload()
    return { decision, attempted: true }
  }

  // Exposed on the hooks so the unload path — the one place that decides to
  // spend an action on the outside world — can be driven directly by a test
  // instead of being only reachable on a five-second timer.
  const runTick = tick

  const timer = setInterval(() => {
    void runTick()
  }, TICK_MS)
  timer.unref()

  // The heartbeat exists because opencode discards the cause of a plugin load
  // failure: a plugin that throws on import produces no log at any level. A
  // missing heartbeat is what makes "the policy silently does not exist" a
  // visible state rather than an absence of evidence.
  writeHeartbeat()
  publishLease()
  log("info", "unload policy loaded", {
    pid,
    instanceId,
    idleThresholdSeconds: config.idleThresholdSeconds,
    settleSeconds: config.settleSeconds,
    backend: config.backend,
  })

  return {
    __tick: runTick,

    event: async ({ event }) => {
      const at = now()
      if (event.type === "session.status") {
        const sessionID = event.properties?.sessionID
        const status = event.properties?.status?.type
        if (!sessionID || !status) return
        touchSession(sessionID, (state, at) => {
          if (status === "busy" || status === "retry") {
            if (!state.busy) state.busyAt = at
            state.busy = true
            noteLocalActivity(state)
          } else if (status === "idle") {
            state.busy = false
          }
        })
        // Published on the transition, not left to the next tick: a peer that
        // reads the lease up to five seconds late could decide to unload while
        // this instance is already generating.
        publishLease()
        return
      }

      if (event.type === "session.deleted") {
        const sessionID = event.properties?.info?.sessionID
        if (sessionID) {
          sessions.delete(sessionID)
          recompute(at)
          publishLease()
        }
        return
      }

      // Any traffic against a local session is activity against the resident
      // model. Without this a long generation would age past the threshold
      // while it was still streaming. These arrive many times a second, so they
      // move the in-memory timestamp only; the next tick publishes it.
      if (event.type === "message.part.delta" || event.type === "message.updated") {
        const sessionID = event.properties?.sessionID
        if (!sessionID) return
        const state = sessions.get(sessionID)
        if (state) noteLocalActivity(state)
      }
    },

    "chat.params": async (input) => {
      const providerID = input.model?.providerID
      if (!providerID) return
      touchSession(input.sessionID, (state) => {
        state.local = providerID === config.localProviderId
        state.model = input.model?.id ?? null
      })
      const state = sessions.get(input.sessionID)
      // Only local traffic refreshes the lease. Cloud work must not hold the
      // resident model for the length of a conversation that never used it.
      if (state?.local) lastLocalActivityAt = now()
      publishLease()
    },

    dispose: async () => {
      clearInterval(timer)
      try {
        rmSync(leasePath(instanceId), { force: true })
      } catch {
        // A lease left behind is stale, not harmful: the reader resolves
        // liveness from the process.
      }
    },
  }
}

export const LlmAgentUnloadPolicy = async (input: PluginInput): Promise<Hooks> => {
  const globals = globalThis as unknown as Record<symbol, Hooks | undefined>
  const existing = globals[SINGLETON]
  if (existing) return existing

  let config: PolicyConfig
  try {
    config = JSON.parse(readFileSync(policyConfigPath(), "utf8")) as PolicyConfig
  } catch (error) {
    // No policy is better than a guessed one. The thresholds are generated from
    // the registry; if they are missing, say so loudly and do nothing.
    const message = `unload policy disabled: ${policyConfigPath()} unreadable (${String(error)})`
    try {
      input.client.app.log({ body: { service: SERVICE, level: "error", message } })
    } catch {
      console.log(`[${SERVICE}] error: ${message}`)
    }
    return {}
  }

  const instanceId = `${process.pid}.${Math.random().toString(36).slice(2, 10)}`
  const hooks = createUnloadPolicy(input, config, instanceId)
  globals[SINGLETON] = hooks
  return hooks
}
