{
  lib,
  errIf,
}: let
  # The plugin is deployed as ONE self-contained file in opencode's plugin
  # directory, built by splicing `decision.ts` and `plugin.ts` together.
  #
  # This is not a stylistic choice. `home.file.<name>.text` compiles each file
  # to its OWN store path, named after the target with separators stripped, not
  # a directory tree. So a relative import from a deployed file resolves against
  # the Nix store: an entry that re-exported `../llm-agent/plugin.js` looked for
  # it beside itself in /nix/store, failed, and — because the loader discards
  # the cause of a plugin load failure — the only symptom was a missing
  # heartbeat. The deployed copy has to stand alone.
  #
  # The seam is still authored and tested as its own module; only the deployed
  # artefact is a concatenation. The splice removes plugin.ts's import of the
  # seam and asserts it was actually removed, so reformatting plugin.ts cannot
  # silently leave a dead import behind (which would fail the same silent way).
  decisionSource = builtins.readFile ./policy/decision.ts;
  pluginSource = builtins.readFile ./policy/plugin.ts;

  # The exact import block, asserted below so a reformat cannot invalidate it.
  seamImport = ''
    import {
      isRepeatUnload,
      shouldUnload,
      type Decision,
      type InflightEntry,
      type Lease,
      type LeaseSet,
    } from "./decision.js"
  '';
  pluginWithoutSeamImport = builtins.replaceStrings ["
${seamImport}"] ["
"] pluginSource;

  # opencode invokes EVERY function export in a plugin file as a plugin
  # factory. The spliced seam brings `createUnloadPolicy`, `isRepeatUnload`
  # and `shouldUnload` along as exports; called with a single plugin input,
  # `createUnloadPolicy` throws on `config.idleThresholdSeconds` and poisons
  # the whole file load — so the real entry never runs and the only symptom is
  # a missing heartbeat. The deployed copy therefore exports exactly one
  # function. Tests import the helpers from the repo sources, never from here.
  deployedSource =
    builtins.replaceStrings
    ["export function createUnloadPolicy(" "export { isRepeatUnload, shouldUnload }"]
    ["function createUnloadPolicy(" ""]
    (decisionSource + "
" + pluginWithoutSeamImport);

  pluginEntry = ''
    // Generated by nixos-flake. Edit policy/decision.ts or policy/plugin.ts,
    // never this file: it is their concatenation.
    ${deployedSource}
  '';

  # `errIf` reports when its condition is FALSE, so "must not contain" is
  # spelled as the *absence* being the passing case.
  pluginErrors =
    errIf (!(lib.hasInfix "decision.js" pluginEntry))
    "the deployed plugin must not reference ./decision.js: it is spliced in, and a live import would resolve against the Nix store and fail to load silently"
    ++ errIf (pluginWithoutSeamImport != pluginSource)
    "the deployed plugin must still contain plugin.ts's source: the seam import it strips was reformatted, so the splice is no longer sound"
    ++ errIf (lib.hasInfix "function shouldUnload" pluginEntry && lib.hasInfix "LlmAgentUnloadPolicy" pluginEntry)
    "the deployed plugin must carry both the decision seam and the plugin entry"
    ++ errIf (!(lib.hasInfix "export function" pluginEntry) && !(lib.hasInfix "export {" pluginEntry))
    "the deployed plugin must export exactly one function: opencode invokes every function export as a plugin factory, and a second one throws on its missing config and poisons the whole file load";
in {
  inherit
    pluginEntry
    pluginErrors
    ;
  files = {
    ".config/opencode/plugins/llm-agent-unload.ts".text = pluginEntry;
  };
}
